### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/sense-hat-random-sparkles#3]
Hey @samalderhyde a few bird's-eye-view Sense HAT illustrations would be excellent for this resource. One with one random pixel, one with two, and one full of random pixels.

For the first one, pick any colour in on any pixel, just let me know the RGB values and I'll use them in the worksheet. Mix it up a bit.

**Comment by lawsie** [comment]
@bennuttall How about if I added either screenshots of the trinket emulator or actual trinkets into the resource, rather than taking up Sam's time?

**Comment by bennuttall** [comment]
That makes sense! (wasn't an option at the time) - please do :+1:

**Comment by lawsie** [comment]
Derp. It appears Marc already did this!
